uploads = []

[[generated]]
id = "c4B5IgvRXc5R0UdyoUENT"
uri = "file://artifacts/aurelix-pitch-deck/public/hero.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "sP1CH7Zs5rAdpJvAz65nQ"
uri = "file://.local/outputs/AURELIX.pdf"
type = "pdf"
title = "AURELIX.pdf"
